### ISSUE TITLE
loc_path = path_to_dropbox + 'Sequences/locations.txt' not found in the Github

### ISSUE THREAD

**Issue by zjgulai** [ebov/space-time#10]
could you upload your locations.txt
loc_path = path_to_dropbox + 'Sequences/locations.txt'

**Comment by evogytis** [comment]
Apologies for that. The `Sequences/locations.txt` simply maps the coordinates of each admin division to its population centroid. The same information (as `Pop_Centroid_X` and `Pop_Centroid_Y`) is available from this file: `https://github.com/ebov/space-time/blob/master/Data/Location_Data_2016-05-27.csv`

**Comment by zjgulai** [comment]
Thank you very much for your kind answer

Gytis Dudas <notifications@github.com> 于2020年2月29日周六 下午9:30写道：

**Comment by zjgulai** [comment]
[image: image.png]
Does the Sequences/locations.txt file only contain this part of the data.
Can you make a new  ‘locations.txt’ file and send it to me? Thank you very
much, I want to do some research in this area.

jian zhou <zhoujianaaa123@gmail.com> 于2020年3月1日周日 上午11:10写道：

**Comment by zjgulai** [comment]
Because the script flow in your github only supports python2 format. The
first thing I want to do is change it to python3 environment, so I need
some help from you, thank you very much for your guidance. After making the
changes, I will resubmit the new documents to you if you need them.

jian zhou <zhoujianaaa123@gmail.com> 于2020年3月1日周日 上午11:17写道：
