### ISSUE TITLE
Does the Sequences/locations.txt file only contain this part of the data？

### ISSUE THREAD

**Issue by zjgulai** [ebov/space-time#11]
Does the Sequences/locations.txt file only contain this part of the data. Can you make a new  ‘locations.txt’ file and send it to me? Thank you very much, I want to do some research in this area.
Because the script flow in your github only supports python2 format. The first thing I want to do is change it to python3 environment, so I need some help from you, thank you very much for your guidance. After making the changes, I will resubmit the new documents to you if you need them.
![image](https://user-images.githubusercontent.com/48468925/75618873-0b95ea00-5baf-11ea-8686-e1b8068d0a92.png)

**Comment by evogytis** [comment]
Yes, that's all the information in the `locations.txt` file. You can just source the population centroid coordinates from there. If you want to make an animation I've rewritten the code for that in python 3 and streamlined it here: https://github.com/evogytis/baltic/blob/master/docs/curonia.ipynb.

**Comment by zjgulai** [comment]
Thank you very much for your help. I am a PhD student from Wuhan, Hubei,
China. I don't just want to simulate through your project, I want to do
some other virus research based on your project. Some files in your
notebook folder, the specific files are in your <squence> folder. Could you
please share your data with me so that I can better understand the essence
of the project. the data need like follows:

Makona_1610_cds_ig.GLM.log

Makona_1610_cds_ig.GLM.history.log



Gytis Dudas <notifications@github.com> 于2020年3月2日周一 上午12:31写道：

**Comment by evogytis** [comment]
Unfortunately all of the `.log` files from BEAST are too big for GitHub. You'll have to run `https://github.com/ebov/space-time/blob/master/Analyses/SpatialGLM/56_location/Makona_1610_cds_ig.joint_GLM.xml` locally to get those files.

**Comment by zjgulai** [comment]
OK， thanks all the same.
Gytis Dudas <notifications@github.com> 于2020年3月2日周一 下午3:16写道：

**Comment by zjgulai** [comment]
Could you tell why we need two group log files to run the
"EBOV_phylogeography_analysis.ipynb" script. I spent 80 hours to get one
group of .log hand history.log.
# lpaths=[path_to_dropbox+'Sequences/Aug2016_1610_genomes/Joint/HomogenousGLM/All_1610/Run%d/Makona_1610_cds_ig.GLM.log'%(run)
for run in range(1,3)]
# hpaths=[path_to_dropbox+'Sequences/Aug2016_1610_genomes/Joint/HomogenousGLM/All_1610/Run%d/Makona_1610_cds_ig.GLM.history.log'%(run)
for run in range(1,3)]
lpaths=['./56_location/Makona_1610_cds_ig.GLM.log']
hpaths=['./56_location/Makona_1610_cds_ig.GLM.history.log']

jian zhou <zhoujianaaa123@gmail.com> 于2020年3月2日周一 下午5:26写道：

**Comment by evogytis** [comment]
They're replicate outputs of an MCMC analysis because it's always good be sure that your independent chains have converged to the same stationary distribution.
