### ISSUE TITLE
Family 'normal' requires scale parameters

### ISSUE THREAD

**Issue by liamxg** [ebov/space-time#12]
Dear @evogytis,

Could you tell me how to solve this:

Loading additional development parsers from development_parsers.properties, which is additional set of parsers only available for development version ...
Parsing XML file: location_glm_LogCladeSize_45_RE_withInt.xml
  File encoding: UTF8
Looking for plugins in /Volumes/SIMON/space-time/Analyses/CaseGLM/plugins
Mar 02, 2024 7:10:56 AM dr.app.beast.BeastMain <init>
SEVERE: Parsing error - poorly formed BEAST file, location_glm_LogCladeSize_45_RE_withInt.xml:
Error parsing '<glmModel>' element with id, 'GLM.glmModel':
Family 'normal' requires scale parameters

Error thrown at: dr.inferencexml.distribution.GeneralizedLinearModelParser.parseXMLObject(Unknown Source)

Constructing a linear regression model

BEAST has terminated with an error. Please select QUIT from the menu.

**Comment by evogytis** [comment]
Dear @liamxg,

Are you running the XML in question in BEAST v.1.8.3?
I believe that's what we would've used back then.

Best,
Gytis

**Comment by liamxg** [comment]
Dear @evogytis,

Sorry for the delay reply,  thanks for your reply.

I find that the `location_glm_LogCladeSize_45_RE_withInt.xml` file is generated by RBeast, could you tell me more about this, for example, the input data and script for this, thanks.

**Comment by evogytis** [comment]
That is a question entirely unrelated to this repository, so I presume your original question has been addressed. Please direct your questions about BEAST to the BEAST repository: https://github.com/beast-dev/beast-mcmc, not here.
