### ISSUE TITLE
Visualizations help

### ISSUE THREAD

**Issue by BEAST-Community** [ebov/space-time#7]
Dear @evogytis,
The video is very cool, is there are pipeline that I can reproducible, thanks.

**Comment by evogytis** [comment]
@BEAST-Community The notebook to produce the video is available here: https://github.com/ebov/space-time/blob/master/Scripts/notebooks/EBOV_phylogeography_animation.ipynb
I have also put a more generalised version of the notebook here: https://github.com/blab/baltic/blob/master/curonia.ipynb
