### ISSUE TITLE
Where can I find the path= path_to_dropbox = '/Users/evogytis/Dropbox/Ebolavirus_Phylogeography/'

### ISSUE THREAD

**Issue by zjgulai** [ebov/space-time#9]
path_to_dropbox = '/Users/evogytis/Dropbox/Ebolavirus_Phylogeography/'
map_path = path_to_dropbox + 'Data_Processing/June2016/'
Can you tell me tha data path?

**Comment by evogytis** [comment]
The map can be found here: https://github.com/ebov/space-time/blob/master/Data/location_data_v3.geojson
